## Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
##
## 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
##
## By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def is_even(n):
	if (n % 2) == 0:
		return True
	else:
		return False

def main():
	i = 1
	j = 1
	acc = 0
	
	s = i + j
	
	while s < 4000000:
		s = i + j
		if is_even(s):
			acc += s
		i = j
		j = s
	
	return acc

print main()