"""The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
"""

def find_divisors(n, divisor_dict):
    divisors = {1}

    for i in range(n//2, 1, -1):
        if i in divisor_dict:
            divisors.add(i)
            divisors | divisor_dict[i]
        elif i not in divisors and n % i == 0:
            divisors.add(i)
            divisors.add(n//i)
    return divisors

mem = {1: 1}

def tri_nums():
    i = 1
    while 1:
        if i in mem:
            yield mem[i]
        else:
            mem[i] = mem[i-1] + i
            yield mem[i]
        i += 1


def main():
    divisor_dict = {1: {1}}
    i = 1
   
    for n in tri_nums():
        if len(find_divisors(n, divisor_dict)) > 500:
            return n

if __name__ == '__main__':
    print(main())
    #i = tri_nums()
    #for _ in range(0, 10):
    #    print(i.__next__())
